apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-app-volume-0
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/devops-projects/proj-1/mysql-test"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-app-volume-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
   path: "/var/lib/devops-projects/proj-1/mysql2"




