apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-pv-app-claim
  namespace: devops-proj-1
spec:
  storageClassName: manual
  volumeName: mysql-pv-app-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi