version: "3.6"
services:
  standalonedb:
    build:
      context: ./..
      dockerfile: ./scripts/backend.Dockerfile
    #env_file:
    #  - ./.env
    image: babycare-backend
    container_name: standalonedb
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
       MYSQL_USER: ${MYSQL_USER} 
       MYSQL_DATABASE: ${DATABASE}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
 
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql:rw
      - ./../db/babyname.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app_net
  app:
    build:
      context: ./..
      dockerfile: ./scripts/Dockerfile
    image: babycare:latest
    container_name: babycare
    depends_on:
      - standalonedb
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       DATABASE_SERVER: ${DATABASE_SERVER}  
       DATABASE_PORT: ${DATABASE_PORT}
       MYSQL_USER: ${MYSQL_USER}  
       MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
       DATABASE: ${DATABASE} 
    #env_file:
     #- ./.env
    networks:
      - app_net
volumes:
  dbdata:
networks:
  app_net: